# docker-compose.yml
version: "3"
services:
  database:
    image: postgres
    environment: # postgres should be getting these variables, not the variables set in the env file thats for localhost
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/pgdata
#      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  pgdata:
